# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Vfor/git/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/ip/Stack_64x10/Stack_64x10.xci
# IP: The module: 'Stack_64x10' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Vfor/git/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/ip/Stack_64x10/Stack_64x10_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Stack_64x10'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/Vfor/git/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/ip/Stack_64x10/Stack_64x10.xci
# IP: The module: 'Stack_64x10' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Vfor/git/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/ip/Stack_64x10/Stack_64x10_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Stack_64x10'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
