# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Vfor/git/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/ip/MemWinner/MemWinner.xci
# IP: The module: 'MemWinner' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Vfor/git/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/ip/MemWinner/MemWinner_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MemWinner'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/Vfor/git/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/ip/MemWinner/MemWinner.xci
# IP: The module: 'MemWinner' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Vfor/git/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/ip/MemWinner/MemWinner_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MemWinner'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
